### ISSUE TITLE
Reason for including the JS and CSS assets?

### ISSUE THREAD

**Issue by berkes** [xtr3me/spree_billing_sisow#5]
Hello,

All asset files merely include spree_backend and spree_frontent CSS. Is that not the task of the integration, the main app including this gem?

Is there a reason we must be sure spree backend and spree frontend CSS and JS is included? If so, that would be a good reason. If not, I could remove them, cleaning up a lot.

FWIW: I'm upgrading to 2-2-stable, which has moved its assets around, which is why I came across this.

**Comment by xtr3me** [comment]
Hi,
I don't know for sure if this is really needed, so I don't have a good reason why we include the css and js from this Gem.
I think the spree generator generated these includes when I was building this gem.
So feel free to customize and optimize this gem :)
